title: Howard Chou
logo: "/images/bio_photo.jpeg?raw=true" # your photo (or logo) here
description: >
  Hello! I'm Howard, a Supply Chain and Data Analyst. This portfolio showcases the projects I’ve completed — feel free to explore.
  <br>
  Skills: SQL, Python, PowerBI, Tableau, R
  <br>
  <br>
  <a href="https://www.linkedin.com/in/hchoward/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
