title: Howard Chou
logo: "/images/bio_photo.png?raw=true" # your photo (or logo) here
description: >
  Supply Chain and Data Analyst. 
  <br>
  <br>
  <a href="https://www.linkedin.com/in/larrychencpa/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
